services:
  music-assistant-server:
    image: ghcr.io/music-assistant/server:latest
    container_name: music-assistant-server
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./data:/data
      - /mnt/Entertainment/Music:/music
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
